# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 365d02d923dbdd298e102aeb3dce3adaea8da5e9f157ba3affd65561124aaf9fe3017af2da6f983937d1c324b0faad2de70118df96620d5e1b76f4abd3a8e7bd

test:
  secret_key_base: fe7f418911316b1909759b7c35173ea6ee09a4201a184c95b0d03eaadfbeaff997fadf5d4431e65934217e75f2c2b762b80f5ddb8d48edf940d3bcd46c2f847e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
